### ISSUE TITLE
Action SelectPlus doorbell transmitter range!

### ISSUE THREAD

**Issue by A-Industry** [athombv/nl.action#13]
I have succesfully paired Homey and the SelectPlus doorbell, but the advertised range of 80m between transmitter and base station is nowhere near reached between the transmitter and Homey. After even 5 meters of clear line of sight the transmission becomes unstable and often nothing happens. Hanging the transmitter near the front door at 7 meters is currently no option. Could this be a problem by the way Homey receives/modulates the 433mhz signal?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2616
