### ISSUE TITLE
Adding second Promax Switch renders the first one unfunctional

### ISSUE THREAD

**Issue by Arjanvde** [athombv/nl.action#4]
When you add a second Promax switch the first device can't be switched any more. When you try the switch the first device the second device responds. The second paired device now has the function to be switched from 2 devices (shown in the my.athom.com Zones & Devices screen)

**Comment by Dennishacq** [comment]
Hi Arjanvde,

Thank you for posting your issue,
I'm not able to reproduce this problem with the latest version.
Please let me know if you are still experiencing this problem with the 1.0.15 update. (which should be in the appstore soon)

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
